global:
  resolve_timeout: 1m

route:
  receiver: default
  group_by: ['region', 'service', 'alert_name', 'severity']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1m

receivers:
  - name: default
    webhook_configs:
      - url: http://eu-app-1:8080/webhook
        send_resolved: false
      - url: http://eu-app-2:8080/webhook
        send_resolved: false
      - url: http://eu-app-3:8080/webhook
        send_resolved: false
