global:
  resolve_timeout: 1m

route:
  receiver: default
  group_by: ['region', 'service', 'alert_name', 'severity']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1m

receivers:
  - name: default
    webhook_configs: []
