extensions:
  file_storage:
    directory: /var/lib/otelcol
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
  batch/logs:
    timeout: 200ms
    send_batch_size: 256

exporters:
  otlphttp/metrics:
    endpoint: http://us-victoriametrics:8428/opentelemetry
    sending_queue:
      enabled: false
    retry_on_failure:
      enabled: true
  otlphttp/logs:
    endpoint: http://us-victorialogs:9428/insert/opentelemetry
    sending_queue:
      enabled: true
      storage: file_storage
    retry_on_failure:
      enabled: true

service:
  extensions: [file_storage, health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlphttp/metrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch/logs]
      exporters: [otlphttp/logs]
